## Get personal information
GET  http://localhost:3001/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6ImFsZWFuZGVycjMzMjMzM0Bob3RtYWlsLmNvbSIsImlhdCI6MTY0NjM2MTczNiwiZXhwIjoxNjQ2MzYyNjM2fQ.Eb-Xyz1-2w46VP0Ibkm_Djzmzdo2wJUE_ds0IHL2EUw


### signin
PATCH  http://localhost:3001/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEyLCJlbWFpbCI6ImFsZWFuZGVycjMzMjMzM0Bob3RtYWlsLmNvbSIsImlhdCI6MTY0NjM2MTczNiwiZXhwIjoxNjQ2MzYyNjM2fQ.Eb-Xyz1-2w46VP0Ibkm_Djzmzdo2wJUE_ds0IHL2EUw

{
    "email": "aleanderr332333@hotmail.com",
    "lastName": "govea"
} 