## login
POST http://localhost:3001/auth/signup
content-type: application/json

{
    "email": "aleanderr@hotmail.com",
    "password": "alexander123"
}  

#  ## signup
# POST http://localhost:3001/auth/signin
# content-type: application/json
 